name: LLM Nightly Build & Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
  #   - cron: '*/5 * * * *' # GMT time, 6:50 GMT == 12:50 China
  workflow_dispatch:
    inputs:
      pypi-version:
        description: 'pypi version (e.g. 2.5.0.dev0)'
        required: false
        default: ''
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-bigdl-core-xxx-for-py311:
    uses: ./.github/workflows/build-pypi-package.yml
    with:
      python-version: '3.11'
      pypi-version: ${{ (github.event_name == 'schedule') && '' || ( github.event_name == 'workflow_dispatch' ) && inputs.pypi-version }}
      release-bigdl-core-xe: true
      release-bigdl-core-xe-win: true
      release-bigdl-core-xe-batch: true
      release-bigdl-core-xe-batch-win: true
      release-bigdl-core-xe-addons-for-linux-and-windows: true

  trigger-bigdl-core-xxx-for-py310:
    needs: trigger-bigdl-core-xxx-for-py311
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build-pypi-package.yml
    with:
      python-version: '3.11'
      pypi-version: ${{ (github.event_name == 'schedule') && '' || ( github.event_name == 'workflow_dispatch' ) && inputs.pypi-version }}
      release-bigdl-core-xe: true
      release-bigdl-core-xe-win: true
      release-bigdl-core-xe-batch: true
      release-bigdl-core-xe-batch-win: true
      release-bigdl-core-xe-addons-for-linux-and-windows: true
